name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: https://ghcr.io
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image (scratch)
        uses: docker/build-push-action@v6
        with:
          file: ./scratch.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/arm64,linux/amd64
      - name: Build and push Docker image (alpine)
        uses: docker/build-push-action@v6
        with:
          file: ./alpine.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:alpine
          platforms: linux/arm64,linux/amd64
